#!/bin/bash
echo "=== Port Connectivity Check ==="
echo ""
echo "Checking if ports are listening locally:"
echo "Port 80 (nginx):"
ss -tlnp | grep ":80 " && echo "✓ Port 80 is listening" || echo "✗ Port 80 is NOT listening"
echo ""
echo "Port 8080 (backend):"
ss -tlnp | grep ":8080 " && echo "✓ Port 8080 is listening" || echo "✗ Port 8080 is NOT listening"
echo ""
echo "Port 3000 (frontend):"
ss -tlnp | grep ":3000 " && echo "✓ Port 3000 is listening" || echo "✗ Port 3000 is NOT listening"
echo ""
echo "=== Testing local connectivity ==="
curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://localhost/ && echo "✓ Nginx responding locally" || echo "✗ Nginx NOT responding"
echo ""
echo "=== Server IP ==="
hostname -I | awk '{print $1}'
echo ""
echo "=== IMPORTANT: Cloud Provider Firewall ==="
echo "If you cannot access from browser, you need to open ports in your cloud provider's firewall:"
echo "  - Port 80 (HTTP)"
echo "  - Port 8080 (Backend API - optional)"
echo "  - Port 3000 (Frontend direct - optional)"
echo ""
echo "Common providers:"
echo "  - AWS: Security Groups"
echo "  - DigitalOcean: Cloud Firewall"
echo "  - Linode: Firewall Rules"
echo "  - Vultr: Firewall Rules"
echo "  - Hetzner: Firewall"
echo "  - Azure: Network Security Groups"

